LEXI [file] REFER [core] EDIT

: usage
  panic" Usage: file2c [-b] VARNAME SRC [OUT]"
;

: 0usage IF RET THEN usage ;


var: src
var: out
var: var_name
var: is_bytes
var: srcdata

0 out!

: out! ( fname )
  " w" file:open! out!
  [ out file:putc ] -> putc
;


: parse_opt
  opt:read! 0usage
  dup " -b" s= [ yes is_bytes! opt:read! 0usage ] when
  s:put var_name!
  opt:read! 0usage s:put src!
  opt:read! [ out! ] when
;


: load src loadfile srcdata! ;


: type is_bytes [ " uint8_t" ] [ " char" ] if ;


: header ( -- )
  " /* This file is generated by " pr src pr
  " . DO NOT EDIT */" prn cr
  type pr space var_name pr " [] = {" pr
;



var: size
var: data
var: count

: indent "     " pr ;

: content
  srcdata filesize size!
  srcdata filedata data!
  0 count!
  size [
    count [ cr indent ] unless
    data + b@ " 0x" pr ff " , " pr
    count inc dup 12 > [ drop 0 ] when count!
  ] for
;


: footer ( -- )
  is_bytes [ " 0x00" pr ] unless  # put null termination
  cr " };" prn
;


: main
  parse_opt
  load
  header
  content
  footer
;

' main turnkey: bin/file2c.ark
