: usage
  panic" Usage: file2c [-b] VARNAME SRC [OUT]"
;

: 0usage IF RET THEN usage ;


var: src
var: out
var: var_name
var: is_bytes
var: srcdata

0 out!

: out! ( fname ) " w" file:open! out! ;


: putc out [ out file:putc ] [ putc ] if ;
: cr    10 putc ;
: space 32 putc ;

: pr ( s -- )
  dup b@ dup 0 = [ 2drop ] ;when
  putc 1 + AGAIN
;

: prn ( s -- ) pr cr ;

: ff ( n -- ) 0xFF and 16 /mod swap >hex putc >hex putc ;



: parse_opt
  opt:read! 0usage
  dup " -b" s= [ yes is_bytes! opt:read! 0usage ] when
  s:put var_name!
  opt:read! 0usage s:put src!
  opt:read! [ out! ] when
;


: load src loadfile srcdata! ;


: type is_bytes [ " uint8_t" ] [ " char" ] if ;


: header ( -- )
  " /* This file is generated by " pr src pr
  " . DO NOT EDIT */" prn cr
  type pr space var_name pr space " = {" prn
;


: footer ( -- )
  is_bytes [ " 0" pr ] unless  # put null termination
  cr " };" prn
;


var: size
var: data
var: count

: indent "     " pr ;

: content
  srcdata filesize size!
  srcdata filedata data!
  0 count!
  size [
    count [ " , " pr ] [ indent ] if
    data + b@ " 0x" pr ff
    count inc dup 12 > [ drop " , " pr cr 0 ] when count!
  ] for
;


: main
  parse_opt
  load
  header
  content
  footer
;

main
