: usage
  panic" Usage: file2c [-b] VARNAME SRC [OUT]"
;

: 0usage IF RET THEN usage ;


var: src
var: out
var: var_name
var: is_bytes
var: srcdata


: parse_opt
  opt:read! 0usage
  dup " -b" s= [ yes is_bytes! opt:read! 0usage ] when
  here s:put var_name!
  opt:read! 0usage
  here s:put src!
  opt:read! [ here s:put ] [ 0 ] out!
;


: load src loadfile srcdata! ;


: type is_bytes [ " uint8_t" ] [ " char" ] if ;


: header ( -- )
  " /* This file is generated by " pr src pr
  ." . DO NOT EDIT */" cr
  type pr space var_name pr space ." = {"
;


: footer ( -- )
  is_bytes [ " 0" pr ] unless  # put null termination
  cr ." };"
;


var: size
var: data
var: count

: indent "     " pr ;

: content
  srcdata filesize size!
  srcdata filedata data!
  0 count!
  size [
    count [ " , " pr ] [ indent ] if
    data + b@ " 0x" pr ff
    count inc dup 12 > [ drop " , " pr cr 0 ] when count!
  ] for
;


: main
  parse_opt
  load
  header
  content
  footer
;

main
