#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <stdarg.h>
#include <getopt.h>
#include <stdint.h>


int is_bytes = 0;


void die(char* fmt, ...) {
  va_list ap;
  va_start(ap, fmt);

  vfprintf(stderr, fmt, ap);
  fprintf(stderr, "\n");
  exit(1);
}


void usage() {
  fprintf(stderr, "Usage: text2c [-hb] VARNAME SRC [OUT]\n");
  exit(1);
}


uint8_t* read_source(char* fname, int* ret_size) {
  FILE* file = fopen(fname, is_bytes ? "rb" : "r");
  if (!file) die("%s: %s", strerror(errno), fname);
  
  // get file size
  fseek(file, 0L, SEEK_END);
  int size = ftell(file);
  *ret_size = size;
  rewind(file);

  // allocate
  uint8_t* source = calloc(sizeof(uint8_t), size + 1);
  if (!source) die("Can't allocate buffer for %s", fname);
  
  // read
  int read = fread(source, 1, size, file);
  if (read < size) die("%s: %s", strerror(errno), fname);
  if (!is_bytes) source[size] = '\0';

  return source;
}


int handle_opts(int argc, char* argv[]) {
  const char* optstr ="hb";

  struct option long_opts[] =
    { { "help",  no_argument, NULL, 'h' },
      { "bytes", no_argument, NULL, 'z' },
    };
  opterr = 0;

  int c;
  int long_index;
  while ((c = getopt_long(argc, argv, optstr, long_opts, &long_index)) != -1) {
    switch (c) {
    case 'h':
      usage();
    case 'b':
      {
        is_bytes = 1;
        break;
      }
    case '?':
      fprintf(stderr, "Unknown option: %c\n", optopt);
      usage();
    }
  }
  
  return optind;
}


int main(int argc, char* argv[]) {
  int argi = handle_opts(argc, argv);
  int restc = argc - argi;
  char** restv = argv + argi;
  if (restc < 2 || restc > 3) usage();

  char* var_name = restv[0];
  char* source_name = restv[1];
  int size = 0;
  uint8_t* source = read_source(source_name, &size);

  FILE* out = stdout;
  if (restc == 3) {
    char* fname = restv[2];
    out = fopen(fname, "w");
    if (!out) die("%s: %s", strerror(errno), fname);
  }
  
  uint8_t* p = source;
  int col = 0;
  char* type = is_bytes ? "uint8_t" : "char";

  fprintf(out, "/* This file is generated by %s. DO NOT EDIT */\n\n", source_name);
  fprintf(out, "%s %s[] = {", type, var_name);
  
  for (int i = 0; i < size; i++) {
    if (col % 12 == 0) fprintf(out, "\n    ");
    fprintf(out, "0x%02x, ", *p);
    p++;
    col++;
  }

  if (!is_bytes) fprintf(out, "0"); // put terminating zero
  fprintf(out, "\n};\n");
  
  return 0;
}
